server:
  servlet:
    context-path: /
  port: 9080
  compression:
    mime-types:
      - application/json

spring:
  application:
    name: cartoes-ms-orquestrador
  jpa:
    open-in-view: false
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          batch_size: 50
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-local.xml

api:
  criarUsuario:
    url: https://...
  adicionarDependente:
    url: https://...
  adicionarCartaoCompra:
    url: https://...
