server:
  servlet:
    context-path: /
  port: 9080
  compression:
    mime-types:
      - application/json

spring:
  application:
    name: cartoes-ms-orquestrador

api:
  criarUsuario:
    url: http://localhost:9081/cartao/principal
  adicionarDependente:
    url: http://localhost:9081/cartao/dependente
  adicionarCartaoCompra:
    url: http://localhost:9082/usuario
  realizarCompra:
    url: http://localhost:9082/compra
  adicinarCompraFatura:
      url: http://localhost:9083/compra
  adicionarUsarioFatura:
    url: http://localhost:9083/usuario
  pegarFatura:
    url: http://localhost:9083
